apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node-db
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: node-db
    spec:
      containers:
      - name: node-db
        image: aminmithil/node-db:latest
        ports:
        - name: node-js-port
          containerPort: 8888
        env:
          - name: MYSQL_HOST
            value: database-0.mysql
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "kubernetes"
