apiVersion: v1
kind: Pod
metadata: 
  name: test-config-map
  labels: 
    app: test-config
spec:
  containers:
  - name: hello-world
    image: aminmithil/node-db:latest
    ports:
    - containerPort: 8081
    volumeMounts:
    - name: config-volume
      mountPath: /src/
  volumes:
    - name: config-volume
      configMap:
        name: node-config
        items:
        - key: data.properties
          path: data.properties
